import Header from "./components/Header";
import InputFields from "./components/InputFields";

function App() {
	const fields = [
		{
			id: "leadtype",
			name: "Lead Type",
			type: "dropdown",
			required: true,
			options: [
				{
					key: "0",
					value: "Please choose one...",
				},
				{
					key: "1",
					value: "Open",
				},
				{
					key: "2",
					value: "Close",
				},
			],
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			multiSelect: true,
			formCategory: "",
			navigation: "",
			apponly: true,
			selectoption: true,
		},
		{
			id: "corporateid",
			name: "Corporate Id",
			type: "text",
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			defaultValue: "",
			formCategory: "",
			navigation: "",
			apponly: true,
		},
		{
			id: "panno",
			name: "Pan No",
			type: "text",
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "panauthentication",
			dependencyEvent: "onchange",
			min: 0,
			max: 10,
			retainInfo: true,
			formCategory: "",
			navigation: "",
			regex: "[A-Z]{5}[0-9]{4}[A-Z]{1}",
			regexerrormsg: "Enter Valid PAN No",
			lengtherrormsg: "Pan No should be 10 character",
			uppercase: true,
		},
		{
			id: "number1",
			name: "Number 1",
			type: "integer",
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "number3",
			dependencyEvent: "onchange",
			tagOperation: "",
			tagAssociatedValue: "",
			formCategory: "",
			navigation: "",
		},
		{
			id: "number2",
			name: "Number 2",
			type: "integer",
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "number3",
			dependencyEvent: "onchange",
			tagOperation: "",
			tagAssociatedValue: "",
			formCategory: "",
			navigation: "",
		},
		{
			id: "number3",
			name: "Addition of 2 Fields",
			type: "integer",
			readOnly: true,
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "subof2fields",
			dependencyEvent: "onchange",
			expression: "{number1}+{number2}",
			intermediateExpression: "{number1}+{number2}",
			tagOperation: "",
			tagAssociatedValue: "",
			formCategory: "",
			navigation: "",
		},
		{
			id: "tradename",
			name: "Trade Name",
			type: "text",
			required: true,
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			defaultValue: "super",
			formCategory: "",
			navigation: "",
			apponly: true,

			lowercase: true,
		},
		{
			id: "registeredaddress",
			name: "Registered Address",
			type: "text",
			required: true,
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			formCategory: "",
			navigation: "",
			apponly: true,
			columncount: 2,
		},
		{
			id: "gender",
			name: "Gender",
			type: "radio-buttons",
			required: true,
			options: [
				{
					key: "Male",
					value: "Male",
				},
				{
					key: "Female",
					value: "Female",
				},
				{
					key: "Others",
					value: "Others",
				},
			],
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			defaultValue: "",
			formCategory: "",
			navigation: "",
			apponly: true,
		},
		{
			id: "primarygstn",
			name: "Primary GSTN",
			type: "integer",
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			minvalue: 10,
			maxvalue: 1000,
			defaultValue: "740",
			tagOperation: "",
			tagAssociatedValue: "",
			formCategory: "",
			navigation: "",
			apponly: true,
			valueerrormsg: "Min value is 10 and Max value should be 1000",
			slider: true,
		},

		{
			id: "rfield1",
			name: "R Field 1",
			type: "text",
			required: true,
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			formCategory: "Visibility",
			navigation: "",
			apponly: true,
			uppercase: true,
		},
		{
			id: "rfield2",
			name: "R Field 2",
			type: "text",
			required: true,
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			formCategory: "Visibility",
			navigation: "",
			apponly: true,
			lowercase: true,
		},
		{
			id: "rfield3",
			name: "R Field 3 ",
			type: "text",
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			formCategory: "Visibility",
			navigation: "",
		},
		{
			id: "rfield4",
			name: "R Field 4",
			type: "text",
			visibilityCondition: "",
			visibilityEvent: "",
			visibilityField: "",
			visibilityOperation: "",
			dependencyCondition: "",
			dependencyEvent: "",
			formCategory: "Visibility",
			navigation: "",
		},
	];

	return (
		<div>
			<Header />
			<InputFields fields={fields} />
		</div>
	);
}

export default App;
